version: '3.8'

services:
  app:
    container_name: django_tutorial_full
    hostname: django_tutorial_full
    build:
      context: .
      dockerfile: Dockerfile
      target: ${ENVIRONMENT}
    ports:
      - "8050:8050"
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:

      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    depends_on:
      - database
      - redis
    networks:
      - default
      - internal_local_network

  database:
    image: postgres:16.8-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - cache-data:/data
    networks:
      - default

volumes:
  postgres_data:
  cache-data:
  static_volume:
  media_volume:

networks:
  default:
  internal_local_network: