version: '3.8'

services:
  app:
    image: django_tutorial
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - backend
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8050"]
  db:
    image: postgres:16.8-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 5
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - cache-data:/data
    networks:
      - backend

volumes:
  postgres_data:
  cache-data:

networks:
  backend:
