# Generated by Django 5.1.7 on 2025-04-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_at',
            new_name='date_modified',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='updated_at',
            new_name='date_modified',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='productimage',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
