# Generated by Django 5.1.7 on 2025-04-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['-name']},
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='date_modified',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('FURNITURE', 'Furniture'), ('CLOTHING', 'Clothing'), ('FOOD', 'Food'), ('TOYS', 'Toys'), ('BOOKS', 'Books'), ('BEAUTY', 'Beauty'), ('SPORTS', 'Sports'), ('JEWELRY', 'Jewelry'), ('AUTOMOTIVE', 'Automotive'), ('HEALTH', 'Health'), ('GARDEN', 'Garden'), ('MUSICAL_INSTRUMENTS', 'Musical Instruments'), ('OFFICE_SUPPLIES', 'Office Supplies'), ('PET_SUPPLIES', 'Pet Supplies'), ('TOOLS', 'Tools'), ('OTHER', 'Other')], max_length=255, unique=True),
        ),
    ]
