# Generated by Django 5.1.7 on 2025-04-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(default='', upload_to='product_images/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
