# Generated by Django 5.1.7 on 2025-04-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_images_delete_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('FURNITURE', 'Furniture'), ('CLOTHING', 'Clothing'), ('FOOD', 'Food'), ('TOYS', 'Toys'), ('BOOKS', 'Books'), ('BEAUTY', 'Beauty'), ('SPORTS', 'Sports'), ('JEWELRY', 'Jewelry'), ('AUTOMOTIVE', 'Automotive'), ('HEALTH', 'Health'), ('GARDEN', 'Garden'), ('MUSICAL_INSTRUMENTS', 'Musical Instruments'), ('OFFICE_SUPPLIES', 'Office Supplies'), ('PET_SUPPLIES', 'Pet Supplies'), ('TOOLS', 'Tools'), ('OTHER', 'Other')], max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
