# Generated by Django 5.1.7 on 2025-03-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=255)),
                ('flight', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('departure_time', models.CharField(max_length=255)),
                ('stops', models.CharField(max_length=255)),
                ('arrival_time', models.CharField(max_length=255)),
                ('destination_city', models.CharField(max_length=255)),
                ('duration', models.FloatField(max_length=255)),
                ('days_left', models.IntegerField(max_length=255)),
                ('price', models.IntegerField(max_length=255)),
            ],
        ),
    ]
