# Generated by Django 5.1.7 on 2025-03-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_flights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='days_left',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flights',
            name='price',
            field=models.IntegerField(),
        ),
    ]
