# Generated by Django 5.1.7 on 2025-03-27 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0005_alter_flights_days_left_alter_flights_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flights',
            old_name='source',
            new_name='source_city',
        ),
    ]
