# Generated by Django 5.1.7 on 2025-03-29 18:53

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0007_alter_address_options_rename_name_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='email', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='phone', max_length=128, region=None,
                                                                 unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('street', 'city', 'state', 'zip_code')},
        ),
    ]
