# Generated by Django 5.1.7 on 2025-03-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
