# Generated by Django 5.1.7 on 2025-03-29 22:24

import django.core.validators
import django.db.models.deletion
import vendors.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('description', 'vendor_email', 'seller_name', 'store_name')},
        ),
        migrations.AddField(
            model_name='vendorreview',
            name='user',
            field=models.ForeignKey(blank=True, default=vendors.models.get_default_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], default='Free', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='seller_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='vendorreview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterUniqueTogether(
            name='vendorbankdetail',
            unique_together={('vendor', 'bank_name', 'account_number', 'swift_code')},
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
    ]
